Yarn এর চিটশিট যোগ করা হয়েছে।
devsonket/devsonket.github.io pull request #345
Opened 2020-10-01 18:49 UTC by shaonkabir8

2020-10-03 14:41 UTC, zonayedpca requested changes
সুপার অসাম! অনেক দরকারি একটা চিটশিট... প্লীজ সামান্য কিছু চেঞ্জ করে আবার পুশ করুন সেইম ব্রাঞ্চেই

2020-10-03 14:41 UTC, zonayedpca commented on data/yarn-cheat-sheet.json
> +  "id": "yarn-cheat-sheet",
জাস্ট ```yarn``` ইউজ করুন... চিটশিট লেখাটা বাদ দিয়ে দিন

2020-10-03 14:41 UTC, zonayedpca commented on data/yarn-cheat-sheet.json
> +  "title": "ইয়ার্ন চিটশিট",
জাস্ট ```ইয়ার্ন ``` ইউজ করুন, চিটশিট লেখাটা বাদ দিন

2020-10-03 19:25 UTC, shaonkabir8 commented on data/yarn-cheat-sheet.json
> +  "id": "yarn-cheat-sheet",
জ্বী ভাই। আপডেট করে দিছি।

2020-10-04 01:57 UTC, zonayedpca approved these changes

2020-10-04 01:57 UTC, merged