Added Cheat Sheet for Figma
devsonket/devsonket.github.io pull request #347
Opened 2020-10-03 10:35 UTC by zubayerhimel

Added a new cheat sheet for design and prototype tool figma.

2020-10-03 15:44 UTC, zonayedpca requested changes

2020-10-03 15:44 UTC, zonayedpca commented on data/figma.json
> +    "slug": "figma-cheat-sheet",
জাস্ট ```figma``` রাখেন, ```-cheat-sheet``` লেখাটা বাদ দিন...

2020-10-03 17:06 UTC, zubayerhimel commented on data/figma.json
> +    "slug": "figma-cheat-sheet",
হাই ভাইয়া, পরিবর্তন করে দিয়েছি

2020-10-04 01:58 UTC, zonayedpca approved these changes

2020-10-04 02:01 UTC, merged