Added Transport Sign
devsonket/devsonket.github.io pull request #391
Opened 2020-10-20 19:02 UTC by asifadib

2020-10-21 01:50 UTC, shaonkabir8 requested changes
সম্ভবত এইগুলো `পরিবহন সাইন` না :cry:

2020-10-21 07:09 UTC, asifadib commented
> সম্ভবত এইগুলো `পরিবহন সাইন` না 😢

ভাইয়া এইসব সাইন তো আমি বানাই নাই আমি বিভিন্ন রিসোর্স থেকে যা পাইছি তাই কালেক্ট করে দিছি। নিচে একটা রেফারেন্স লিংক দিলাম চেক করে নিবেন। 

https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md#transport-sign

ভালো বা প্রয়জনীয় মনে হলে একচেপ্ট করবেন নাহয় রিজেক্ট করে দিতে পাড়েন। 

ধন্যবাদ।

2020-10-21 07:28 UTC, shaonkabir8 commented
> ভালো বা প্রয়জনীয় মনে হলে একচেপ্ট করবেন নাহয় রিজেক্ট করে দিতে পাড়েন।
> 
> ধন্যবাদ।


ভাইয়া আমিও আপনার মত একজন কন্ট্রিবিউটর মাত্র। একসেপ্ট করা বা রিজেক্ট করার অধিকার আমার নাই ভাইয়া 😪

যাইহোক, আপনি আমার কথায় হয়তো রাগ করেছেন। তার জন্য আমি আন্তরিকভাবে দুঃখিত। 🙏

2020-10-21 07:35 UTC, asifadib commented
> > ভালো বা প্রয়জনীয় মনে হলে একচেপ্ট করবেন নাহয় রিজেক্ট করে দিতে পাড়েন।
> > ধন্যবাদ।
> 
> ভাইয়া আমিও আপনার মত একজন কন্ট্রিবিউটর মাত্র। একসেপ্ট করা বা রিজেক্ট করার অধিকার আমার নাই ভাইয়া 😪
> 
> যাইহোক, আপনি আমার কথায় হয়তো রাগ করেছেন। তার জন্য আমি আন্তরিকভাবে দুঃখিত। 🙏

রাগ করার কিছুই নাই ভাইয়া। আপনারা সিনিয়র ভাইয়ারা ভুল না ধরাইয়া দিলে আমরা ছোটারা শিখবো কোথায় থেকে। আমি রিপ্লে দিতে গিয়ে আমার আচরন খারাপ হলে আমি দুঃখিত @shaonkabir8 ভাই

2020-10-21 07:46 UTC, shaonkabir8 commented
> রাগ করার কিছুই নাই ভাইয়া। আপনারা সিনিয়র ভাইয়ারা ভুল না ধরাইয়া দিলে আমরা ছোটারা শিখবো কোথায় থেকে। আমি রিপ্লে দিতে গিয়ে আমার আচরন খারাপ হলে আমি দুঃখিত @shaonkabir8 ভাই


না ভাইয়া। আমি হয়তো অন্যভাবেও বলতে পারতাম।  তার জন্য আমি দুঃখিত ভাই।
ভুল বুঝাবুঝির এখানেই অবসান হোক 🙏 

Happy Contributing 🚀

2020-10-21 07:57 UTC, shaonkabir8 approved these changes

2020-10-23 17:26 UTC, zonayedpca approved these changes
দুই একটা সাইন পরিবহন সাইন এর মধ্যে পড়ে কিনা শিউর হতে পারছি না, বাট এটা ব্যাপার না...

2020-10-23 17:26 UTC, merged