Added Punctuation emoji
devsonket/devsonket.github.io pull request #394
Opened 2020-10-20 19:54 UTC by asifadib

2020-10-21 01:48 UTC, shaonkabir8 requested changes
Hi Mate :wave: 
Instead creating Four separated PRs for a single file,  It'd be awesome to create a single PRs with (or without)  multiple commits. :rocket: 

Thanks.

2020-10-21 07:17 UTC, asifadib commented
> Hi Mate 👋
> Instead creating Four separated PRs for a single file, It'd be awesome to create a single PRs with (or without) multiple commits. 🚀
> 
> Thanks.

ভাইয়া আমি যখনই সুযোগ পাই একটু একটু করে কন্ট্রিবিউশন করার চেষ্টা করি। ধন্যবাদ পরবর্তীতে আপনার পরামার্শ অনুসরণ করার চেষ্টা করবো।

2020-10-21 07:40 UTC, shaonkabir8 commented
> ভাইয়া আমি যখনই সুযোগ পাই একটু একটু করে কন্ট্রিবিউশন করার চেষ্টা করি। 

জ্বী ভাইয়া।  আমিও এইভাবে কন্ট্রিবিউট করি।

2020-10-23 17:29 UTC, zonayedpca approved these changes

2020-10-24 16:05 UTC, merged