Added Google Sheets Shortcuts
devsonket/devsonket.github.io pull request #397
Opened 2020-10-25 19:05 UTC by asifadib

2020-10-26 18:34 UTC, shaonkabir8 approved these changes
অসাধারণ :heart: 
গুগল শিট খুবই দরকারী :fire: এত সুন্দর একটা চিটশিটের জন্য ধন্যবাদ। :rocket:

2020-10-26 19:28 UTC, asifadib commented
> অসাধারণ ❤️
> গুগল শিট খুবই দরকারী 🔥 এত সুন্দর একটা চিটশিটের জন্য ধন্যবাদ। 🚀

ধন্যবাদ ভাইয়া ❤️❤️

2020-10-27 08:19 UTC, zonayedpca requested changes

2020-10-27 08:19 UTC, zonayedpca commented on data/Google-Sheets-Shortcuts.json
> +  "id": "Google-Sheets-Shortcuts",
ছোটো হাতের করে দিনঃ ```google-sheets-shortcuts```

2020-10-27 08:19 UTC, zonayedpca commented on data/Google-Sheets-Shortcuts.json
> +  "slug": "Google-Sheets-Shortcuts",
ছোটো হাতের করে দিনঃ ```google-sheets-shortcuts```

2020-10-27 08:27 UTC, zonayedpca approved these changes

2020-10-27 09:12 UTC, merged