added flutter cheatsheet
devsonket/devsonket.github.io pull request #452
Opened 2021-01-29 16:25 UTC by mirajus-salehin

As flutter is growing in popularity, so I thought it's good to have a cheatsheet of flutter. The cheatsheet was difficult to write as JSON, so I have made it with Github flavored markdown.

What's inside the cheatsheet?

- Basics of flutter
-  Many useful codes like slider, radio button, loading indicator
- Special cheat for creating a responsive header

2021-01-30 04:14 UTC, shaonkabir8 approved these changes
অসাধারণ চিটশিটের জন্য আপনাকে ধন্যবাদ। :heart:

2021-01-30 14:22 UTC, mirajus-salehin commented
- new cheatsheet added for R
- cheatsheet for flutter cannot be formatted as instructed because JSON doesn't support multiline strings. I've tried to make the code object a minified string but it's a mess and will be hard to maintain.

2021-01-30 17:45 UTC, shaonkabir8 commented on data/r.json
> +    "title": "বেসিক R চিটশিট",
'বেসিক R চিটশিট' এর পরিবর্তে 'R প্রোগ্রামিং' দিতে পারেন।

2021-01-30 17:48 UTC, shaonkabir8 requested changes

2021-01-30 17:48 UTC, shaonkabir8 commented on data/r.json
> +    "title": "বেসিক R চিটশিট",
'বেসিক R চিটশিট' এর পরিবর্তে 'R প্রোগ্রামিং' দিতে পারেন।

2021-01-31 04:46 UTC, mirajus-salehin commented on data/r.json
> +    "title": "বেসিক R চিটশিট",
সাজেশনের জন্য ধন্যবাদ। :heart:

2021-01-31 06:25 UTC, mirajus-salehin reviewed
```title``` object changed as requested

2021-01-31 09:20 UTC, sabbirshawon approved these changes

2021-01-31 09:21 UTC, merged