Update & Remove `NextJs` Links
devsonket/devsonket.github.io pull request #614
Opened 2021-11-06 17:14 UTC by Rafat97

This is a nice repo. 
I like this very much. 

Thank you for making this types of repo.  I am give the special thanks of the contributor and the owner for growing our bangla community.  😀❤️‍🔥

Thank you.

2021-11-07 19:07 UTC, sabbirshawon requested changes

2021-11-07 19:07 UTC, sabbirshawon commented on data/nextjs.json
> +               "definition":"নেক্সট জেএস ইমেজ ওপ্তিমাইজ",
fix the spelling optimize in bangla

2021-11-09 05:27 UTC, Rafat97 commented on data/nextjs.json
> +               "definition":"নেক্সট জেএস ইমেজ ওপ্তিমাইজ",
Fix this. Check

2021-11-11 04:01 UTC, sabbirshawon approved these changes

2021-11-11 04:02 UTC, merged