How to Comment in the Rust program
devsonket/devsonket.github.io pull request #797
Opened 2022-10-15 17:07 UTC by morshedulmunna

How to Comment in the Rust program multi and single line comments

2022-10-15 17:24 UTC, zonayedpca approved these changes

2022-10-15 17:25 UTC, zonayedpca requested changes
দয়া করে একটু কনফ্লিক্ট রিসল্ভ করে দিতে পারবেন কি? একইসাথে সেইম ফাইলে একটা ব্রাঞ্চেই কাজ করবেন, তাহলে এরকম কনফ্লিক্ট হবে না... ধন্যবাদ...

2022-10-15 17:29 UTC, morshedulmunna commented
Okay

2022-10-21 17:09 UTC, zonayedpca approved these changes

2022-10-21 17:09 UTC, merged