Update js-array-methods.json
devsonket/devsonket.github.io pull request #880
Opened 2022-10-30 10:19 UTC by mdmahinpro

new method added

2022-10-31 04:01 UTC, sabbirshawon commented on data/js-array-methods.json
> +                    "code": "arr.of("A", "B", "C")"
fix this line

2022-10-31 04:01 UTC, sabbirshawon requested changes
fix the problem and send pr again... dont use " " within " "

2022-11-05 06:57 UTC, fahadali32 commented
"arr.of('A', 'B', 'C')"
use this

2022-11-05 08:01 UTC, mdmahinpro reviewed
error fixed

2022-12-06 04:18 UTC, shaonkabir8 approved these changes

2022-12-06 04:18 UTC, merged